### ISSUE TITLE
Toggling comments (block or line) does not work

### ISSUE THREAD

**Issue by odyssomay** [skoch/Sublime-ActionScript-3#1]
As title says.

**Comment by skoch** [comment]
@odyssomay I'm using default settings (command + /) and all is working for me. Can you open up Comments.tmPreferences and change line 17 to something like:

&lt;string&gt;// testing &lt;/string&gt;

to see if that outputs anything?

**Comment by odyssomay** [comment]
Oh, I'm sorry. I didn't realize I was using the default syntax provided by sublime text. If I change the syntax to `ActionScript 3` as provided by this plugin, it works as intended.
