### ISSUE TITLE
Crash when use a set function

### ISSUE THREAD

**Issue by gaglage** [skoch/Sublime-ActionScript-3#2]
When you define a 'public -function set functionName(param)- the plugin crashes and you notice that all the code wrote below is printed as plain text

**Comment by skoch** [comment]
@gaglage Not sure I follow how you're crashing the plugin. Can you walk me through the steps to re-create?

**Comment by gaglage** [comment]
Hi @skoch 
Type this, and you can watch that I mean
package  {

```
public class Example {

    public function Example() {
        // constructor code
    }

}

public function get data(){}

public function set data(){}
```

}

**Comment by skoch** [comment]
Your getter/setter for 'data' isn't defined in the class.

``` actionscript
package {
    class Example {
        private var _data:String;
        public function Example() {
            // constructor code
        }
        public function get data():String {
            return _data;
        }
        public function set data( $value:String ):void {
            _data = $value;
        }
    }
}
```

**Comment by gaglage** [comment]
You're right, that's a simple example, but I notice in my real code I wasn't setting the output type for setter (:void). If you don't declare it the problem continues.
Thanks a lot!

``` actionscript
package {
    class Example {
        private var _data:String;
        public function Example() {
            // constructor code
        }
        public function get data():String {
            return _data;
        }
        public function set data( $value:String ) {
            _data = $value;
        }
        public function checkData( $value:String ){
            //
        }
    }
}
```

**Comment by skoch** [comment]
Think of it as a way to know that you're code is 'broken' or you're missing something. You need to declare variable types as well as return types!

**Comment by p-kolacz** [comment]
Declaring function return type isn't mandatory. Syntax highlight should work without it.

**Comment by skoch** [comment]
Both of these work for me, is this what you mean?

``` actionscript
package foobar
{
    public class FoobarCode
    {
        public var bar;
        public function someFunction( $arg )
        {
            trace( "someFunction ", $arg, bar );
        }
    }
}

package foobaz
{
    public class FoobazCode
    {
        public var baz:String;
        public function someOtherFunction( $arg:String ):String
        {
            trace( "someOtherFunction ", $arg, baz );
            return $arg;
        }
    }
}

```

**Comment by p-kolacz** [comment]
Problem is with setter functions:

``` actionscript
public function set type(newType)
{
    _type = newType
}
```

**Comment by skoch** [comment]
Yes, you're correct. The plugin fails to properly highlight after any setter that isn't declaring the return type `void`. In this case, I suggest you update your code to have the `void` as opposed to not.

Is it mandatory? I'm not sure, but in every example out there that I can see (in the 3 minute search just now) declares the return type of `void`.
